### PR TITLE
Add config to deactivate the ranges

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by pablogsal** [comment]
@isidentical Can you give me privileges to the repo, please?

**Comment by isidentical** [comment]
Done

**Comment by pablogsal** [comment]
Thanks! I'm merging this then

**Comment by isidentical** [comment]
@pablogsal cool, I've merged your changes into my branch https://github.com/colnotab/cpython/pull/2/commits/bde32937c5ec35c4761d7c8fdd2667adc2d0306d

**Pull request merged**
